"""empty message

Revision ID: 767fa90901c3
Revises: f07cc7b46a95
Create Date: 2024-04-29 14:13:17.771400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767fa90901c3'
down_revision = 'f07cc7b46a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tee_time',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tee_time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tee_time_id'], ['teetimes.id'], name=op.f('fk_user_tee_time_tee_time_id_teetimes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tee_time_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'tee_time_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tee_time')
    # ### end Alembic commands ###
