"""empty message

Revision ID: af5cb2ac013d
Revises: 767fa90901c3
Create Date: 2024-04-29 14:42:31.359711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5cb2ac013d'
down_revision = '767fa90901c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tee_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tee_time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tee_time_id'], ['teetimes.id'], name=op.f('fk_users_tee_times_tee_time_id_teetimes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_tee_times_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_tee_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tee_time',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tee_time_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tee_time_id'], ['teetimes.id'], name='fk_user_tee_time_tee_time_id_teetimes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_tee_time_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'tee_time_id')
    )
    op.drop_table('users_tee_times')
    # ### end Alembic commands ###
