"""empty message

Revision ID: b488abdd28f3
Revises: d37be3a69947
Create Date: 2024-04-22 18:02:48.408986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b488abdd28f3'
down_revision = 'd37be3a69947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], name=op.f('fk_scores_course_courses')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_scores_user_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
