"""empty message

Revision ID: c850e12200f8
Revises: b488abdd28f3
Create Date: 2024-04-25 16:27:05.276455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c850e12200f8'
down_revision = 'b488abdd28f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_members_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_members_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tee_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('slots_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_tee_times_course_id_courses')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tee_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tee_time_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tee_time_id'], ['tee_times.id'], name=op.f('fk_tee_time_slots_tee_time_id_tee_times')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tee_time_slots_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tee_time_slots')
    op.drop_table('tee_times')
    op.drop_table('course_members')
    # ### end Alembic commands ###
